-- Create table
create table APPLICATION_PERSON
(
  person_first_name    VARCHAR2(255),
  person_last_name     VARCHAR2(255),
  person_rc_num        VARCHAR2(15),
  person_birth_date    VARCHAR2(20),
  person_city_of_birth VARCHAR2(255)
);

-- Create unique index 
create unique index APPLICATION_PERSON_NK on APPLICATION_PERSON(person_rc_num);

-- Insert data
insert into APPLICATION_PERSON (PERSON_FIRST_NAME, PERSON_LAST_NAME, PERSON_RC_NUM, PERSON_BIRTH_DATE, PERSON_CITY_OF_BIRTH)
values ('JAN', 'NOVÁK', '7001017895', '01.01.1970', 'PRAHA');

insert into APPLICATION_PERSON (PERSON_FIRST_NAME, PERSON_LAST_NAME, PERSON_RC_NUM, PERSON_BIRTH_DATE, PERSON_CITY_OF_BIRTH)
values ('JANA', 'NOVÁKOVÁ', '7252249987', '24.02.1972', 'PLZEŇ');

insert into APPLICATION_PERSON (PERSON_FIRST_NAME, PERSON_LAST_NAME, PERSON_RC_NUM, PERSON_BIRTH_DATE, PERSON_CITY_OF_BIRTH)
values ('FILIP', 'SVOBODA', '9007026684', '02.07.1990', 'BRNO');

insert into APPLICATION_PERSON (PERSON_FIRST_NAME, PERSON_LAST_NAME, PERSON_RC_NUM, PERSON_BIRTH_DATE, PERSON_CITY_OF_BIRTH)
values ('JITKA', 'NĚMCOVÁ', '0202020022', '02.02.2002', 'HRADEC KRÁLOVÉ');

insert into APPLICATION_PERSON (PERSON_FIRST_NAME, PERSON_LAST_NAME, PERSON_RC_NUM, PERSON_BIRTH_DATE, PERSON_CITY_OF_BIRTH)
values ('HANA', 'KUČEROVÁ', '9959151436', '15.09.1999', 'BRNO');

insert into APPLICATION_PERSON (PERSON_FIRST_NAME, PERSON_LAST_NAME, PERSON_RC_NUM, PERSON_BIRTH_DATE, PERSON_CITY_OF_BIRTH)
values ('PETR', 'HORÁK', '9512242236', '24.12.1995', 'PRAHA');

commit;