merge into dw_partner tgt
using (select
   PARTNER_RC_NUM,
   PARTNER_FIRST_NAME,
   PARTNER_LAST_NAME,
   PARTNER_FULL_NAME,
   PARTNER_BIRTH_DATE,
   PARTNER_BIRTH_CITY,
   PARTNER_SOURCE_SYSTEM 
from VT_DW_PARTNER_CRM) src
on (src.PARTNER_RC_NUM = tgt.PARTNER_RC_NUM
    and src.PARTNER_SOURCE_SYSTEM = tgt.PARTNER_SOURCE_SYSTEM)
when not matched then insert (   PARTNER_RC_NUM,
   PARTNER_FIRST_NAME,
   PARTNER_LAST_NAME,
   PARTNER_FULL_NAME,
   PARTNER_BIRTH_DATE,
   PARTNER_BIRTH_CITY,
   PARTNER_SOURCE_SYSTEM )    
values (   src.PARTNER_RC_NUM,
   src.PARTNER_FIRST_NAME,
   src.PARTNER_LAST_NAME,
   src.PARTNER_FULL_NAME,
   src.PARTNER_BIRTH_DATE,
   src.PARTNER_BIRTH_CITY,
   src.PARTNER_SOURCE_SYSTEM )
when matched then update set
   tgt.PARTNER_FIRST_NAME = tgt.PARTNER_FIRST_NAME,
   tgt.PARTNER_LAST_NAME = src.PARTNER_LAST_NAME,
   tgt.PARTNER_FULL_NAME = src.PARTNER_FULL_NAME,
   tgt.PARTNER_BIRTH_DATE = src.PARTNER_BIRTH_DATE,
   tgt.PARTNER_BIRTH_CITY = src.PARTNER_BIRTH_CITY;

commit;